[package]
name = "signal"
version.workspace = true
edition.workspace = true

[dependencies]
webrtc.workspace = true
tokio.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
async-trait.workspace = true
env_logger = "0.11"
anyhow.workspace = true
matchbox_signaling.workspace = true
bytes.workspace = true
clap.workspace = true
dashmap.workspace = true
common = {path = "../common"}
