//! Common types and methods that `peer` and `signal` both use.
#![allow(unused)]
use serde::{Deserialize, Serialize};
use webrtc::peer_connection::RTCSessionDescription;
use uuid::Uuid;

/// Message(s) to be exchanged via WebSocket between the signaling server and any peer.
/// We assume 1 channel only, and each peer only has 1 SDP offer. Hopefully adding more than
/// 1 channel isn't going to be difficult.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub enum WsExchangeMsg {
    // Join isn't needed, creating the WebSocket channel is inferred as a join request.

    /// Response to a join request, from the signaling server, with the peer ID.
    JoinPeerId(Uuid),
    /// When a peer first joins, other peers are broadcasted the new peer's UUID. The peers already
    /// in the channel waits for the new peer's offer for each of them.
    NewPeer {
        peer_id: Uuid,
    },
    /// When a peer first joins, that peer receives other peer's UUIDs. This peer creates offers for
    /// each of the existing peer.
    ExistingPeer {
        peer_id: Uuid,
    },
    /// Offer or answer generated by a peer.
    Sdp {
        send_to_id: Uuid,
        answering_peer_id: Uuid,
        sdp: RTCSessionDescription,
    },
    /// A peer just left
    LeavePeerId(Uuid),
}
